import = [
  "~/.config/alacritty/tokyonight_night.toml"
]
 
[window.padding]
x = 10
y = 10

[font]
normal = { family = "Iosevka", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 13


